// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GooglePlayIds
{
        public const string achievement_skilled_attacker = "CgkI7ff8sYEBEAIQBQ"; // <GPGSID>
        public const string achievement_getting_started = "CgkI7ff8sYEBEAIQBw"; // <GPGSID>
        public const string achievement_heavy_hitter = "CgkI7ff8sYEBEAIQBA"; // <GPGSID>
        public const string achievement_rookie = "CgkI7ff8sYEBEAIQAQ"; // <GPGSID>
        public const string achievement_honorable_defender = "CgkI7ff8sYEBEAIQBg"; // <GPGSID>
        public const string achievement_upgrade_master = "CgkI7ff8sYEBEAIQAw"; // <GPGSID>

}

